api_platform:
    title: C3net Core Bundle API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    graphql:
        enabled: true
    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        graphql: [ 'application/graphql' ]
