c3net_core:
    api_platform:
        enable_swagger: true
        title: 'C3net Core API'
        version: '1.0.0'
        description: 'Comprehensive business and project management API'
    
    jwt:
        enabled: true
        ttl: 3600
        algorithm: 'RS256'
    
    audit:
        enabled: true
        ignored_columns: ['createdAt', 'updatedAt']
    
    entity_traits:
        auto_uuid: true
        auto_timestamps: true
        auto_soft_delete: true
        auto_blameable: true
    
    cors:
        enabled: true
        allow_origin: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'