# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_suffix: '_audit'
            viewer: true

            ignored_columns:
                - 'createdAt'
                - 'updatedAt'

            # audited entities
            entities:
                App\Entity\Category: ~
                App\Entity\Company: ~
                App\Entity\CompanyGroup: ~
                App\Entity\Contact: ~
                App\Entity\DomainEntityPermission: ~
                App\Entity\Project: ~
                App\Entity\User: ~
