# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_suffix: '_audit'
            viewer: true

            ignored_columns:
                - 'createdAt'
                - 'updatedAt'

            # audited entities  
            entities:
                C3net\CoreBundle\Entity\Category: ~
                C3net\CoreBundle\Entity\Company: ~
                C3net\CoreBundle\Entity\CompanyGroup: ~
                C3net\CoreBundle\Entity\Contact: ~
                C3net\CoreBundle\Entity\Project: ~
                C3net\CoreBundle\Entity\User: ~
