easy_admin:
    design:
        # Custom brand styling
        brand:
            color: '#343a40'
        # Menu configuration
        menu:
            # Override default menu styling
            css_class: 'ea-menu-custom'
        # Form theme
        form_themes:
            - '@EasyAdmin/crud/form_theme.html.twig'
