framework:
    rate_limiter:
        comments_per_10m:
            policy: 'token_bucket'
            limit: 30
            rate: { interval: '600 seconds', amount: 30 }
            cache_pool: cache.rate_limiter
        votes_per_10m:
            policy: 'token_bucket'
            limit: 60
            rate: { interval: '600 seconds', amount: 60 }
            cache_pool: cache.rate_limiter
