services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Auto-register all services in the bundle
    C3net\CoreBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Enum/'

    # Console Commands
    C3net\CoreBundle\Command\:
        resource: '../src/Command/'
        tags: ['console.command']

    # Controllers
    C3net\CoreBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # API Platform State Providers/Processors
    C3net\CoreBundle\State\:
        resource: '../src/State/'

    # Event Listeners
    C3net\CoreBundle\EventListener\:
        resource: '../src/EventListener/'

    # Repositories should NOT be autowired - they're handled by Doctrine
    # Services that need repositories should inject EntityManagerInterface instead

    # Services
    C3net\CoreBundle\Service\:
        resource: '../src/Service/'

    # Data Fixtures - temporarily disabled due to repository dependency issues
    # C3net\CoreBundle\DataFixtures\:
    #     resource: '../src/DataFixtures/'
    #     tags: ['doctrine.fixture.orm']

    # Doctrine Listeners
    C3net\CoreBundle\Doctrine\Listener\:
        resource: '../src/Doctrine/Listener/'

    # API Processors
    C3net\CoreBundle\Api\Processor\:
        resource: '../src/Api/Processor/'

    # Domain Services
    C3net\CoreBundle\Domain\:
        resource: '../src/Domain/'

    # Form Types
    C3net\CoreBundle\Form\Type\:
        resource: '../src/Form/Type/'

    # OpenApi Configuration
    C3net\CoreBundle\OpenApi\:
        resource: '../src/OpenApi/'

    # Repository services are handled automatically by Doctrine
    # No need to manually define them as services
