parameters:
  app.locales:
    - de
    - en
    - es
    - fr
    - it
    - nl
    - se
    - zh_TW   
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: ../src/
twig:
  globals:
    image_placeholder: 'https://picsum.photos/1920/1080?random=9'
    image_placeholder_portrait: 'https://picsum.photos/1080/1520?random=9'
