services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Auto-register all services in the bundle
    C3net\CoreBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Enum/'

    # Console Commands
    C3net\CoreBundle\Command\:
        resource: '../src/Command/'
        tags: ['console.command']

    # Controllers
    C3net\CoreBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # API Platform State Providers/Processors
    C3net\CoreBundle\State\:
        resource: '../src/State/'

    # Event Listeners
    C3net\CoreBundle\EventListener\:
        resource: '../src/EventListener/'

    # Repositories should NOT be autowired - they're handled by Doctrine
    # Services that need repositories should inject EntityManagerInterface instead

    # Services
    C3net\CoreBundle\Service\:
        resource: '../src/Service/'

    # Password Change Notification Service needs explicit from email configuration
    C3net\CoreBundle\Service\PasswordChangeNotificationService:
        arguments:
            $mailFrom: 'noreply@example.com'

    # Data Fixtures - temporarily disabled due to repository dependency issues
    # C3net\CoreBundle\DataFixtures\:
    #     resource: '../src/DataFixtures/'
    #     tags: ['doctrine.fixture.orm']

    # Doctrine Listeners
    C3net\CoreBundle\Doctrine\Listener\:
        resource: '../src/Doctrine/Listener/'

    # API Processors
    C3net\CoreBundle\Api\Processor\:
        resource: '../src/Api/Processor/'

    # Domain Services
    C3net\CoreBundle\Domain\:
        resource: '../src/Domain/'

    # Form Types
    C3net\CoreBundle\Form\Type\:
        resource: '../src/Form/Type/'

    # OpenApi Configuration
    C3net\CoreBundle\OpenApi\:
        resource: '../src/OpenApi/'

    # OpenAPI Decorators
    C3net\CoreBundle\OpenApi\UserInfoDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments:
            - '@.inner'
        tags:
            - { name: 'api_platform.openapi.factory.decorator', priority: 10 }

    # State Processors
    # First, UserWriteProcessor decorates the persist processor to hash passwords
    C3net\CoreBundle\State\UserWriteProcessor:
        decorates: 'api_platform.doctrine.orm.state.persist_processor'
        decoration_priority: 2
        arguments:
            - '@.inner'
            - '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'
            - '@C3net\CoreBundle\Service\PasswordHistoryService'
            - '@limiter.password_change'
            - '@doctrine.orm.entity_manager'

    # Then, UserGroupWriteProcessor decorates UserWriteProcessor to handle relationships
    C3net\CoreBundle\State\UserGroupWriteProcessor:
        decorates: 'C3net\CoreBundle\State\UserWriteProcessor'
        decoration_priority: 1
        arguments:
            - '@.inner'
            - '@doctrine.orm.entity_manager'

    # Rate Limiter Storage for password changes
    limiter.password_change.storage:
        class: Symfony\Component\RateLimiter\Storage\CacheStorage
        arguments:
            - '@cache.rate_limiter'

    # Rate Limiter Factory for password changes
    limiter.password_change:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config:
                id: 'password_change'
                policy: 'sliding_window'
                limit: 3
                interval: '1 hour'
            $storage: '@limiter.password_change.storage'

    # Repository services are handled automatically by Doctrine
    # No need to manually define them as services
